backend:
  name: github
  repo: Robgito/blogpostsSKLO # Replace with your Git repository
  branch: main # Replace with the branch you want to use

media_folder: "src/assets/blogposts" # Where uploaded files are stored
public_folder: "/assets/blogposts" # Public path to uploaded files

collections:
  - name: "posts" # Name in the CMS
    label: "Posts"
    folder: "src/assets/blogposts" # Folder to store files
    create: true
    slug: "{{slug}}" # Filename generation pattern
    fields: # Fields for posts
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
